// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/016887356bd795bdd5c6e4074aa3c86d344fffe102226118b7e75087fe02de22.ts";
import * as $1 from "./routes/2b6ef1fd5632066c64ea44a0b606254458afefd93beab939fa085feb1b800bb5.tsx";
import * as $2 from "./routes/3a0123f398c33d606be123460d0733052ffa3a8c507a23c4e5c3beaa57320ed8.tsx";
import * as $3 from "./routes/6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d.ts";
import * as $4 from "./routes/7d3e80bb34762ed682169a0165e87d7b9c65409e1065c44c2e5442961c9e62b3.ts";
import * as $5 from "./routes/82545ef77064c713c679dab8ff668d530bf2e7c3f3a6adc49797575ff5813c5f.ts";
import * as $6 from "./routes/9eb12cc1cc5294076a08d37475dbe9bfbbe51c2cef5f439cee6fd2ce7ee0f659.tsx";
import * as $$0 from "./islands/3a0123f398c33d606be123460d0733052ffa3a8c507a23c4e5c3beaa57320ed8.tsx";
import * as $$1 from "./islands/9eb12cc1cc5294076a08d37475dbe9bfbbe51c2cef5f439cee6fd2ce7ee0f659.tsx";

const manifest = {
  routes: {
    "./routes/016887356bd795bdd5c6e4074aa3c86d344fffe102226118b7e75087fe02de22.ts":
      $0,
    "./routes/2b6ef1fd5632066c64ea44a0b606254458afefd93beab939fa085feb1b800bb5.tsx":
      $1,
    "./routes/3a0123f398c33d606be123460d0733052ffa3a8c507a23c4e5c3beaa57320ed8.tsx":
      $2,
    "./routes/6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d.ts":
      $3,
    "./routes/7d3e80bb34762ed682169a0165e87d7b9c65409e1065c44c2e5442961c9e62b3.ts":
      $4,
    "./routes/82545ef77064c713c679dab8ff668d530bf2e7c3f3a6adc49797575ff5813c5f.ts":
      $5,
    "./routes/9eb12cc1cc5294076a08d37475dbe9bfbbe51c2cef5f439cee6fd2ce7ee0f659.tsx":
      $6,
  },
  islands: {
    "./islands/3a0123f398c33d606be123460d0733052ffa3a8c507a23c4e5c3beaa57320ed8.tsx":
      $$0,
    "./islands/9eb12cc1cc5294076a08d37475dbe9bfbbe51c2cef5f439cee6fd2ce7ee0f659.tsx":
      $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
